/**
 * SMS Gateway interface for the Huawei E3372 LTE stick.
 * 
 * By default the E3372 launches a web-server when pluggend
 * into a pc and allows to send SMS messages through a web-interface.
 * 
 * This module mimics the interaction between the web-interface and the web-server
 * to send SMS messages.
 * 
 * In order to send an SMS through the send-sms endpoint the client needs a session cookie
 * and a verification token that can be retrieved by using the SesTokInfo endpoint.
 * 
 * The actual request is stated in XML format.
 */

import { Message } from "./sendJob";
import axios from "axios";
import { parseString } from "xml2js";
import moment from "moment";

const SESSION_URL = "http://192.168.8.1/api/webserver/SesTokInfo";
const SEND_SMS_URL = "http://192.168.8.1/api/sms/send-sms";

interface SessionInfo {
  session: string;
  token: string;
}

/**
 * Triggers an SMS send request on the E3372 LTE stick.
 * 
 * @param message - The message to be sent.
 */
export function sendMessage(message: Message) {
  return new Promise((resolve, reject) => {
    getSessionInfo()
      .then((sessionInfo) => {
        const headers = generateHeaders(sessionInfo);
        const messageRequest = generateMessageRequest(message);
        axios.post(SEND_SMS_URL, messageRequest, headers).then((response) => {
          resolve(response);
        });
      })
      .catch((err) => reject(err));
  });
}

/**
 * Generates the HTTP header for the SMS send request.
 * 
 * The E3372 LTE stick expects certain header data to be provided
 * when requesting an SMS transmission.
 * 
 * The headers generated by this method are a copy of the headers being send
 * by the E3372 web interface.
 * 
 * @param sessionInfo - Session info containing session cookie and verification token
 */
function generateHeaders(sessionInfo: SessionInfo) {
  const { session, token } = sessionInfo;
  return {
    headers: {
      Host: "192.168.8.1",
      Accept: "*/*",
      "Accept-Language": "de,en-US;q=0.7,en;q=0.3",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
      __RequestVerificationToken: token,
      "X-Requested-With": "XMLHttpRequest",
      "Content-Length": "227",
      Origin: "http://192.168.8.1",
      Connection: "keep-alive",
      Referer: "http://192.168.8.1/html/smsinbox.html?smsinbox",
      Cookie: session,
    },
  };
}

/**
 * Provides a session cookie and verification token to be used when
 * communicating with the E3372 LTE stick.
 */
export function getSessionInfo(): Promise<SessionInfo> {
  return new Promise((resolve, reject) => {
    axios.get(SESSION_URL).then((response) => {
      const xmlData = response.data;
      parseString(xmlData, function (error, result) {
        if (error) {
          reject(error);
        }
        console.log(result);
        resolve({
          session: result.response.SesInfo[0],
          token: result.response.TokInfo[0],
        });
      });
    });
  });
}

/**
 * Generates an SMS send request as expected by the E3372 LTE stick.
 * 
 * @param message 
 */
function generateMessageRequest(message: Message) {
  const { text, recipient, timestamp } = message;
  return `<?xml version="1.0" encoding="UTF-8"?>
          <request>
              <Index>-1</Index>
              <Phones>
                    <Phone>${recipient}</Phone>
              </Phones>
              <Sca></Sca>
              <Content>${text}</Content>
              <Length>${text.length}</Length>
              <Reserved>1</Reserved>
              <Date>${moment(timestamp).format("YYYY-MM-DD HH:mm:ss")}</Date>
          </request>`;
}
